name: Feature request
description: Suggest an idea for this project
title: "[FEATURE] <title>"
labels:
  - enhancement
assignees:
  - danieleguglietti
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking time to help us to improve our library with your ideas.
  - type: textarea
    id: idea
    attributes:
      label: Your Idea
      description: Tell us all about what you expect to see in the library!
      placeholder: I'd like you to add...
      render: Markdown
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: Help us organizing you idea with a task list!
      placeholder: |
        - [ ] Command Executor
      value: |
        - [ ]
      render: Markdown
    validations:
      required: false